### ISSUE TITLE
Add bip44 support

### ISSUE THREAD

**Issue by stdevAlDen** [fibercrypto/skywallet-go#161]
**Feature description**

Describe the feature

**Is your feature request related to a problem? Please describe.**
Get the possibility to work with the [new bip44 feature](https://github.com/fibercrypto/skywallet-mcu/issues/339) from firmware.

**Describe the solution you'd like**
Add a new flag for the command involving the bip44 feature

**Additional context**
https://github.com/fibercrypto/skywallet-mcu/issues/339

**Comment by olemis** [comment]
fixed in 64371a1
