### ISSUE TITLE
Add a Proxy implementation to force the commands to be atomic

### ISSUE THREAD

**Issue by stdevAlDen** [fibercrypto/skywallet-go#163]
**Feature description**

Add a new `Devicer` implementation that proxify the current one (`Device`) to make the commands atomic operation.

**Is your feature request related to a problem? Please describe.**
Some commands require multiple messages, sending an unexpected message breaks the protocol and make the original command to fail or exit. Forcing the command to be atomics solve this problem.

**Describe the solution you'd like**
Use the proxy pattern.

**Describe alternatives you've considered**
Solving thi in the desktop wallet is not reusable.

**Additional context**
https://github.com/fibercrypto/fibercryptowallet/issues/139

**Possible implementation**
Just use a proxy pattern.

**Comment by olemis** [comment]
fixed in 0688a8e
